"""
Centralized Pydantic models for python_adapter_server.

All request/response models are consolidated here for easier maintenance and discovery.
"""

# Common models (error envelopes, pagination, streaming)
from .common import (
    ErrorCode,
    ErrorDetail,
    ErrorResponse,
    PaginationMeta,
    PaginatedResponse,
    paginate,
    SuccessResponse,
    MessageResponse,
    ChatStreamEvent,
    ChatStreamDelta,
)

# Autopilot models
from .autopilot import (
    AutopilotStatusResponse,
    AutopilotEnableRequest,
    AutopilotPolicySetRequest,
    AutopilotEmergencyActionRequest,
    PolicyInfo,
    EventLogEntry,
)

# Pipeline models
from .pipeline import (
    PipelineRequest,
    PipelineTaskSubmitResponse,
    PipelineTaskStatusResponse,
    BatchProcessRequest,
)

# Skills models
from .skills import (
    SkillCompatibilityPayload,
    ScriptPolicyPayload,
    SkillDescriptorPayload,
    SkillSecurityAssessmentPayload,
    SkillPackPayload,
    CapabilityPayload,
    WritingActionPayload,
    RunActionRequest,
    RunActionAcceptedPayload,
    ImportUserSkillRequest,
    ImportUserSkillManifestPayload,
    ImportUserSkillResponse,
    SkillToggleResponse,
    SkillTestRunResponse,
    SkillRuntimeSettingsUpdate,
    SkillRuntimeSettingsResponse,
    SkillApprovalRequestCreate,
    SkillApprovalRequestPayload,
    SkillApprovalDecisionCreate,
    SkillApprovalDecisionPayload,
    SkillApprovalDetailPayload,
    SkillUninstallResponse,
    SkillRollbackRequest,
    SkillRollbackResponse,
    SkillExportResponse,
)

# Runtime models
from .runtime import (
    TaskState,
    CreateSessionRequest,
    SessionPayload,
    CreateJobRequest,
    JobPayload,
    JobStatusPayload,
    EventPayload,
    JobEventSnapshotPayload,
    ArtifactPayload,
    WritingWorkflowStateRequest,
    WritingWorkflowStatePayload,
    MaterialProcessingPageRangePayload,
    MaterialProcessingPreservePayload,
    MaterialProcessingInputRefPayload,
    MaterialProcessingCachePayload,
    MaterialProcessingArtifactPayload,
    MaterialProcessingTaskRequest,
    MaterialProcessingTaskPayload,
    ResearchObjectPayload,
    ResearchEventPayload,
    ResearchProjectionPayload,
    TimelineItemPayload,
    TimelinePagePayload,
    CheckpointPayload,
    ResumeSessionPayload,
    RewindSessionRequest,
    ForkSessionRequest,
    SkillRunResultPayload,
)

# Tool outcome models
from .tool_outcome import (
    AttemptStatus,
    NextActionKind,
    OutcomeQuality,
    OutcomeStatus,
    TOOL_OUTCOME_SCHEMA_VERSION,
    ToolAttempt,
    ToolNextAction,
    ToolOutcome,
)

# Memory models
from .memory import (
    MemoryStatusPayload,
    MemorySearchRequest,
    MemorySearchHitPayload,
    MemorySearchResponsePayload,
    MemoryWakeupPayload,
    MemorySyncPayload,
)

# Resources models
from .resources import (
    ProjectPayload,
    SourceFolderRefPayload,
    SectionPayload,
    MaterialPayload,
    ChunkSearchRefMetadataPayload,
    ChunkSearchRefPayload,
    ChunkSearchRefsResponse,
    FigureTableCandidatePayload,
    DraftPayload,
    RevisionPayload,
    ProjectExportEvidenceProvenancePayload,
    ProjectExportSourceAnchorPayload,
    ProjectExportEvidenceRowPayload,
    ProjectExportCitationChainPayload,
    ProjectExportReviewFindingPayload,
    ProjectExportFigureAssetPayload,
    ProjectExportBibliographyEntryPayload,
    ProjectExportPayload,
    AssociationSignalPayload,
    AssociationAnglePayload,
    EvidenceGapPayload,
    WritingAssociationPayload,
    CreateProjectRequest,
    CreateSectionRequest,
    CreateMaterialRequest,
    CreateDraftRequest,
    SaveDraftRequest,
    BuildAssociationRequest,
    OutlineItemPayload,
    OutlinePayload,
    GenerateOutlineRequest,
    CitationAnchorPayload,
    CitationSourcePayload,
    CitationSourceUpdate,
    CitationSuggestionPayload,
    SuggestCitationsRequest,
    FigureAssetPayload,
    CreateFigureAssetRequest,
    UpdateFigureAssetRequest,
    GenerateFigureAssetsRequest,
    GenerateFigureAssetsResponse,
    SubmitForReviewRequest,
    SubmissionResponsePayload,
    ExportProjectRequest,
)

# Project reasoning bias models
from .project_reasoning_bias import (
    ProjectReasoningBiasFieldSuggestions,
    ProjectReasoningBiasOptimizeRequest,
    ProjectReasoningBiasOptimizeResponse,
    ProjectReasoningBiasOptimizeScope,
    ProjectReasoningBiasPayload,
    ProjectReasoningBiasScopes,
    ProjectReasoningBiasUpdateRequest,
)

# Recovery models
from .recovery import (
    RecoveryEventPayload,
    EventTimelinePayload,
    MemoryFactPayload,
    MemorySnapshotPayload,
    InvalidFactRequest,
    FactInvalidationPayload,
    EventFilterPayload,
    TimelineQueryRequest,
    TimelineQueryResponse,
    RecommendationEvidencePayload,
    RecoveryRecommendationPayload,
    RecommendationsResponsePayload,
)

# Evidence models
from .evidence import (
    PDF_URL_BBOX_UNIT,
    PdfAnchorFields,
    PdfBboxUnit,
    PdfEvidenceAnchorPayload,
    SourceLabelPayload,
    CreateSourceLabelRequest,
    UpdateSourceLabelRequest,
    EvidenceRefPayload,
    EvidenceRefsResponse,
    ChunkLocatorPayload,
    DiscussionEvidencePackPayload,
    EvidencePackBuildRequest,
    EvidencePackBuildResponse,
    EvidenceLocatorCoveragePayload,
    EvidencePackReferencePayload,
    EvidenceRetrievalDiagnosticsPayload,
    RetrievalQrelsStatusPayload,
    JournalMetricEvidencePayload,
    JournalMetricEvidenceSet,
    CitationOverlapPayload,
    CitationVerificationAnchorPayload,
    CitationVerificationPayload,
    CitationVerificationRequest,
    CitationVerificationStatus,
    CitationVerificationsResponse,
    coerce_pdf_bbox,
    pdf_bbox_matches_unit,
)

__all__ = [
    # Common
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "PaginationMeta",
    "PaginatedResponse",
    "paginate",
    "SuccessResponse",
    "MessageResponse",
    "ChatStreamEvent",
    "ChatStreamDelta",
    # Autopilot
    "AutopilotStatusResponse",
    "AutopilotEnableRequest",
    "AutopilotPolicySetRequest",
    "AutopilotEmergencyActionRequest",
    "PolicyInfo",
    "EventLogEntry",
    # Pipeline
    "PipelineRequest",
    "PipelineTaskSubmitResponse",
    "PipelineTaskStatusResponse",
    # Skills
    "SkillCompatibilityPayload",
    "ScriptPolicyPayload",
    "SkillDescriptorPayload",
    "SkillSecurityAssessmentPayload",
    "SkillPackPayload",
    "CapabilityPayload",
    "WritingActionPayload",
    "RunActionRequest",
    "RunActionAcceptedPayload",
    "ImportUserSkillRequest",
    "ImportUserSkillManifestPayload",
    "ImportUserSkillResponse",
    "SkillToggleResponse",
    "SkillTestRunResponse",
    "SkillRuntimeSettingsUpdate",
    "SkillRuntimeSettingsResponse",
    "SkillApprovalRequestCreate",
    "SkillApprovalRequestPayload",
    "SkillApprovalDecisionCreate",
    "SkillApprovalDecisionPayload",
    "SkillApprovalDetailPayload",
    "SkillUninstallResponse",
    "SkillRollbackRequest",
    "SkillRollbackResponse",
    "SkillExportResponse",
    # Runtime
    "TaskState",
    "CreateSessionRequest",
    "SessionPayload",
    "CreateJobRequest",
    "JobPayload",
    "JobStatusPayload",
    "EventPayload",
    "JobEventSnapshotPayload",
    "ArtifactPayload",
    "WritingWorkflowStateRequest",
    "WritingWorkflowStatePayload",
    "MaterialProcessingPageRangePayload",
    "MaterialProcessingPreservePayload",
    "MaterialProcessingInputRefPayload",
    "MaterialProcessingCachePayload",
    "MaterialProcessingArtifactPayload",
    "MaterialProcessingTaskRequest",
    "MaterialProcessingTaskPayload",
    "ResearchObjectPayload",
    "ResearchEventPayload",
    "ResearchProjectionPayload",
    "TimelineItemPayload",
    "TimelinePagePayload",
    "CheckpointPayload",
    "ResumeSessionPayload",
    "RewindSessionRequest",
    "ForkSessionRequest",
    "SkillRunResultPayload",
    # Tool outcome
    "AttemptStatus",
    "NextActionKind",
    "OutcomeQuality",
    "OutcomeStatus",
    "TOOL_OUTCOME_SCHEMA_VERSION",
    "ToolAttempt",
    "ToolNextAction",
    "ToolOutcome",
    # Memory
    "MemoryStatusPayload",
    "MemorySearchRequest",
    "MemorySearchHitPayload",
    "MemorySearchResponsePayload",
    "MemoryWakeupPayload",
    "MemorySyncPayload",
    # Resources
    "ProjectPayload",
    "SourceFolderRefPayload",
    "SectionPayload",
    "MaterialPayload",
    "ChunkSearchRefMetadataPayload",
    "ChunkSearchRefPayload",
    "ChunkSearchRefsResponse",
    "FigureTableCandidatePayload",
    "DraftPayload",
    "RevisionPayload",
    "ProjectExportEvidenceProvenancePayload",
    "ProjectExportSourceAnchorPayload",
    "ProjectExportEvidenceRowPayload",
    "ProjectExportCitationChainPayload",
    "ProjectExportReviewFindingPayload",
    "ProjectExportFigureAssetPayload",
    "ProjectExportBibliographyEntryPayload",
    "ProjectExportPayload",
    "AssociationSignalPayload",
    "AssociationAnglePayload",
    "EvidenceGapPayload",
    "WritingAssociationPayload",
    "CreateProjectRequest",
    "CreateSectionRequest",
    "CreateMaterialRequest",
    "CreateDraftRequest",
    "SaveDraftRequest",
    "BuildAssociationRequest",
    "OutlineItemPayload",
    "OutlinePayload",
    "GenerateOutlineRequest",
    "CitationAnchorPayload",
    "CitationSourcePayload",
    "CitationSourceUpdate",
    "CitationSuggestionPayload",
    "SuggestCitationsRequest",
    "FigureAssetPayload",
    "CreateFigureAssetRequest",
    "UpdateFigureAssetRequest",
    "GenerateFigureAssetsRequest",
    "GenerateFigureAssetsResponse",
    "SubmitForReviewRequest",
    "SubmissionResponsePayload",
    "ExportProjectRequest",
    # Project reasoning bias
    "ProjectReasoningBiasFieldSuggestions",
    "ProjectReasoningBiasOptimizeRequest",
    "ProjectReasoningBiasOptimizeResponse",
    "ProjectReasoningBiasOptimizeScope",
    "ProjectReasoningBiasPayload",
    "ProjectReasoningBiasScopes",
    "ProjectReasoningBiasUpdateRequest",
    # Recovery
    "RecoveryEventPayload",
    "EventTimelinePayload",
    "MemoryFactPayload",
    "MemorySnapshotPayload",
    "InvalidFactRequest",
    "FactInvalidationPayload",
    "EventFilterPayload",
    "TimelineQueryRequest",
    "TimelineQueryResponse",
    "RecommendationEvidencePayload",
    "RecoveryRecommendationPayload",
    "RecommendationsResponsePayload",
    # Evidence
    "PDF_URL_BBOX_UNIT",
    "PdfAnchorFields",
    "PdfBboxUnit",
    "PdfEvidenceAnchorPayload",
    "SourceLabelPayload",
    "CreateSourceLabelRequest",
    "UpdateSourceLabelRequest",
    "EvidenceRefPayload",
    "EvidenceRefsResponse",
    "ChunkLocatorPayload",
    "DiscussionEvidencePackPayload",
    "EvidencePackBuildRequest",
    "EvidencePackBuildResponse",
    "EvidenceLocatorCoveragePayload",
    "EvidencePackReferencePayload",
    "EvidenceRetrievalDiagnosticsPayload",
    "RetrievalQrelsStatusPayload",
    "JournalMetricEvidencePayload",
    "JournalMetricEvidenceSet",
    "CitationOverlapPayload",
    "CitationVerificationAnchorPayload",
    "CitationVerificationPayload",
    "CitationVerificationRequest",
    "CitationVerificationStatus",
    "CitationVerificationsResponse",
    "coerce_pdf_bbox",
    "pdf_bbox_matches_unit",
]
