import { render, screen, within } from '@testing-library/react';
import { describe, expect, it } from 'vitest';

import { DesktopAcceptanceAgentWorkspace } from './DesktopAcceptanceAgentWorkspace';

describe('DesktopAcceptanceAgentWorkspace', () => {
  it('renders the local readiness fixture without private Zotero paths', () => {
    render(<DesktopAcceptanceAgentWorkspace />);

    expect(screen.getByTestId('desktop-acceptance-agent-workspace')).toBeInTheDocument();
    expect(screen.getByRole('region', { name: '本地就绪面板' })).toHaveAttribute('data-density', 'desktop-acceptance');
    expect(screen.getByRole('heading', { name: '本地就绪' })).toBeInTheDocument();
    expect(screen.getByText('工作流检查')).toBeInTheDocument();
    expect(screen.getByText('Zotero 附件')).toBeInTheDocument();
    expect(screen.getByText('单篇精读')).toBeInTheDocument();
    expect(screen.getByText('Review Queue')).toBeInTheDocument();
    expect(screen.getByText('导出与审计')).toBeInTheDocument();
    expect(screen.getByText('Scan the project source folder so retrieval and evidence packs can read chunks.')).toBeInTheDocument();
    expect(screen.getByText('Provide a Zotero data directory containing zotero.sqlite, then rerun the health check.')).toBeInTheDocument();
    expect(screen.getByText('打开任务详情检查待补充哨兵和 evidence refs。')).toBeInTheDocument();
    const wikiImportRecoveryRegion = screen.getByRole('region', { name: 'Wiki import recovery' });
    expect(within(wikiImportRecoveryRegion).getByText('Wiki Import Recovery')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('pending 1')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('runtime refs 1')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('gate block 1')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('read-only true')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('review queue only')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('desktop-import-runtime-note')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('private/imports/runtime-note.md')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('requested final')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('gate block')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('job_wiki_import_acceptance')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('session_wiki_import_acceptance')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('approval_wiki_import_acceptance')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('handoff card available')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('review probe available')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('direct_zotero_db_write')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('external_upload')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('auto_approve_import')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).getByText('No auto approval, external upload, Zotero DB mutation, or published knowledge write is exposed from Agent Workspace.')).toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).queryByRole('button', { name: /approve|write|link/i })).not.toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).queryByRole('link')).not.toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).queryByText('/runtime/job/job_wiki_import_acceptance/agent-handoff-card')).not.toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).queryByText('C:\\Users\\Alice\\My Documents\\runtime note.md')).not.toBeInTheDocument();
    expect(within(wikiImportRecoveryRegion).queryByText(/My Documents/)).not.toBeInTheDocument();
    const workspaceStateRegion = screen.getByRole('region', { name: 'Workspace state visibility' });
    expect(within(workspaceStateRegion).getByText('changed 14')).toBeInTheDocument();
    expect(within(workspaceStateRegion).getByText('main · changed 14 · staged 0 · unstaged 14 · untracked 3')).toBeInTheDocument();
    expect(within(workspaceStateRegion).getByText('ahead 56')).toBeInTheDocument();
    expect(within(workspaceStateRegion).getByText('frontend/src/pages/DesktopAcceptanceAgentWorkspace.tsx')).toBeInTheDocument();
    expect(within(workspaceStateRegion).getByText('frontend/src/pages/DesktopAcceptanceAgentWorkspace.test.tsx')).toBeInTheDocument();
    expect(within(workspaceStateRegion).getAllByText('docs/plans/longrun-goal-state-2026-06-22-scholar-ai-research-workflow-spine.json').length).toBeGreaterThan(1);
    expect(within(workspaceStateRegion).getByText('goal-state 82 rows · proved 82 · incomplete 0 · out-of-scope 0 · latest N74-wiki-import-desktop-acceptance')).toBeInTheDocument();
    expect(within(workspaceStateRegion).getByText('requirement status visible')).toBeInTheDocument();
    const desktopSmokeRegion = within(workspaceStateRegion).getByRole('region', { name: 'Desktop smoke evidence' });
    expect(within(desktopSmokeRegion).getByText('Desktop Smoke Evidence')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('desktop smoke visible')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('read-only true')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('status passed')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('n74-wiki-import-recovery-desktop-aligned · passed · screenshot nonblank · a11y tree yes · candidates 2 · ignored 1')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('/__desktop_acceptance/agent-workspace')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('expected /__desktop_acceptance/agent-workspace')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('ignored 1')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('root 文献助手')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('control 窗口')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('nodes 20')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('named 9')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('workspace_artifacts/generated/desktop_smoke/n74-wiki-import-recovery-desktop-aligned/window.png')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).getByText('workspace_artifacts/generated/desktop_smoke/n74-wiki-import-recovery-desktop-aligned/accessibility-tree.json')).toBeInTheDocument();
    expect(within(desktopSmokeRegion).queryByText(/C:\\Users\\/)).not.toBeInTheDocument();
    const ocrRuntimeRegion = within(workspaceStateRegion).getByRole('region', { name: 'OCR runtime recovery' });
    expect(within(ocrRuntimeRegion).getByText('OCR Runtime')).toBeInTheDocument();
    expect(within(ocrRuntimeRegion).getByText('ocr runtime visible')).toBeInTheDocument();
    expect(within(ocrRuntimeRegion).getByText('selected mock_local')).toBeInTheDocument();
    expect(within(ocrRuntimeRegion).getByText('ocr auto · selected mock_local · ready 1/2 · lang en · source default')).toBeInTheDocument();
    expect(within(ocrRuntimeRegion).getByText('Mock Local OCR · ready · available · local')).toBeInTheDocument();
    expect(within(ocrRuntimeRegion).getByText('Remote OCR API · configuration_required · unavailable · remote · network · blocker api_key is required')).toBeInTheDocument();
    expect(within(ocrRuntimeRegion).getByText('blocker remote_api: api_key is required')).toBeInTheDocument();
    expect(within(ocrRuntimeRegion).getByText('next Inspect literature.ocr_health before claiming OCR execution readiness.')).toBeInTheDocument();
    expect(within(workspaceStateRegion).queryByText(/open requirements/)).not.toBeInTheDocument();
    expect(within(workspaceStateRegion).queryByRole('textbox', { name: 'Filter open requirements' })).not.toBeInTheDocument();
    const requirementDrilldownRegion = within(workspaceStateRegion).getByRole('region', { name: 'Requirement evidence drilldown' });
    expect(within(requirementDrilldownRegion).getByText('Requirement Evidence')).toBeInTheDocument();
    expect(within(requirementDrilldownRegion).getByText('drilldown visible')).toBeInTheDocument();
    expect(within(requirementDrilldownRegion).getByText('read-only true')).toBeInTheDocument();
    expect(within(requirementDrilldownRegion).getByText('evidence 4')).toBeInTheDocument();
    expect(within(requirementDrilldownRegion).getByText('N74-wiki-import-desktop-acceptance · proved')).toBeInTheDocument();
    expect(within(requirementDrilldownRegion).getByText('frontend/src/pages/DesktopAcceptanceAgentWorkspace.tsx · Desktop acceptance fixture renders WikiImportRecoveryPanel with local Markdown import runtime recovery metadata.')).toBeInTheDocument();
    expect(within(requirementDrilldownRegion).getByText('workspace_artifacts/generated/desktop_smoke/n74-wiki-import-recovery-desktop/window.png · Source desktop screenshot visibly shows Wiki Import Recovery in the 文献助手 window.')).toBeInTheDocument();
    expect(within(requirementDrilldownRegion).getByText('boundary No push, tag, release, deploy, external upload, approval execution, or Zotero DB mutation.')).toBeInTheDocument();
    expect(within(workspaceStateRegion).getByText('full goal status visible')).toBeInTheDocument();
    expect(within(workspaceStateRegion).getByText('slice completion N74 completed desktop Wiki Import Recovery acceptance with screenshot and UIA host-tree evidence.')).toBeInTheDocument();
    expect(within(workspaceStateRegion).getByText('full goal The long-running Scholar AI research workflow spine remains active, not complete.')).toBeInTheDocument();
    expect(within(workspaceStateRegion).getByText('checkpoint 20260623-194244-n74-main-wiki-import-desktop-acceptance')).toBeInTheDocument();
    expect(within(workspaceStateRegion).queryByText(/C:\\Users\\xiao\\/)).not.toBeInTheDocument();
    expect(screen.getByRole('region', { name: '研究流程主干' })).toHaveAttribute('data-density', 'desktop-acceptance');
    expect(screen.getByRole('heading', { name: '研究流程' })).toBeInTheDocument();
    expect(screen.getByText('Workflow Passport')).toBeInTheDocument();
    expect(screen.getByText('Evidence Integrity Gate')).toBeInTheDocument();
    expect(screen.getAllByText('Agent Handoff').length).toBeGreaterThan(0);
    const crosslinkRegion = screen.getByRole('region', { name: 'Research action crosslinks' });
    expect(within(crosslinkRegion).getByText('Research Action Crosslinks')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('crosslinks 4')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('lifecycle read-only true')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('passport refs 1')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('gate refs 1')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('handoff refs 1')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('boundary probes 1')).toBeInTheDocument();
    expect(within(crosslinkRegion).getAllByText('runtime.research_action_lifecycle_refs').length).toBeGreaterThan(0);
    expect(within(crosslinkRegion).getAllByText('export_overwrite:job_export_acceptance · export_overwrite · blocked · citation_review · read-only true').length).toBeGreaterThan(1);
    expect(within(crosslinkRegion).getByText('Read research action lifecycle · read-only true')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('handoff action refs 1')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('scoped action refs 1')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('blocked actions 1')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('pending confirmations 1')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('missing preflight 0')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('Do not execute approvals from the handoff action-lifecycle recovery bundle.')).toBeInTheDocument();
    expect(within(crosslinkRegion).getByText('Do not mutate [redacted-local-path] from this read-only projection.')).toBeInTheDocument();
    expect(within(crosslinkRegion).queryByText(/C:\\Users\\Alice\\private\\desktop-acceptance\.pdf/)).not.toBeInTheDocument();
    expect(screen.getAllByText('Evidence pack').length).toBeGreaterThan(0);
    expect(screen.getAllByText('Unsupported citation anchors block export readiness.').length).toBeGreaterThan(0);
    expect(screen.getAllByText('unresolved 1').length).toBeGreaterThan(0);
    expect(screen.queryByText('C:/private/Zotero')).not.toBeInTheDocument();
  });
});
