# sync-roles.ps1 — Single-direction charter → role-file copier.
#
# Replaces the old hardlink approach. Reason: Windows Edit tooling (and any
# `squad update` that rewrites `.squad/roles/*.md` in-place) breaks hardlinks
# silently, leaving charter and role file out of sync. A plain copy + DO NOT
# EDIT banner is robust to both.
#
# Direction:
#   .claude_squad/agents/<role>/charter.md   (source of truth, hand-edited)
#     →  .squad/roles/<role>.md              (generated, banner on top)
#
# Never writes back. Never touches orphan role files (ones without a matching
# charter — e.g. official-squad defaults inspector/manager/worker).
#
# Usage:
#   .\tools\squad\sync-roles.ps1                 # sync all, print summary
#   .\tools\squad\sync-roles.ps1 -DryRun         # report what would change
#   .\tools\squad\sync-roles.ps1 -Role morpheus  # sync just one
#   .\tools\squad\sync-roles.ps1 -Force          # rewrite even if identical
#
# Exit codes:
#   0  = success (or nothing to do)
#   1  = at least one charter source missing
#   2  = write failure

param(
    [string]$Role,
    [switch]$DryRun,
    [switch]$Force,
    [switch]$Quiet
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$OutputEncoding = [System.Text.Encoding]::UTF8
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}

$scriptDir   = $PSScriptRoot
$projectRoot = Split-Path -Parent (Split-Path -Parent $scriptDir)
$charterRoot = Join-Path $projectRoot '.claude_squad\agents'
$rolesRoot   = Join-Path $projectRoot '.squad\roles'

if (-not (Test-Path $charterRoot)) {
    [Console]::Error.WriteLine("charter root missing: $charterRoot")
    exit 1
}
if (-not (Test-Path $rolesRoot)) {
    New-Item -ItemType Directory -Path $rolesRoot -Force | Out-Null
}

function Write-Info {
    param([string]$Msg, [string]$Color = 'Gray')
    if (-not $Quiet) { Write-Host $Msg -ForegroundColor $Color }
}

function Get-Banner {
    param([string]$RoleName)
    $ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz'
    return @"
<!-- ============================================================
     AUTO-GENERATED FROM .claude_squad/agents/$RoleName/charter.md
     DO NOT EDIT THIS FILE DIRECTLY.
     Changes made here are overwritten on the next 'squad spawn',
     'squad doctor', or manual 'tools/squad/sync-roles.ps1' run.
     Edit the charter, then re-sync.
     Generated: $ts
     ============================================================ -->

"@
}

function Test-BodyEquivalent {
    param([string]$RolePath, [string]$NewBody)
    if (-not (Test-Path $RolePath)) { return $false }
    $current = Get-Content $RolePath -Raw -Encoding UTF8
    # Strip any prior auto-generated banner so we only compare content.
    $currentStripped = $current -replace '(?s)^<!--\s*=+\s*AUTO-GENERATED.*?=+\s*-->\s*', ''
    return ($currentStripped -eq $NewBody)
}

# ------------------------------------------------------------------
# Enumerate charters
# ------------------------------------------------------------------
$charters = Get-ChildItem $charterRoot -Directory -ErrorAction SilentlyContinue | ForEach-Object {
    $c = Join-Path $_.FullName 'charter.md'
    if (Test-Path $c) { [PSCustomObject]@{ Role = $_.Name; Charter = $c } }
}

if ($Role) {
    $charters = @($charters | Where-Object { $_.Role -eq $Role })
    if (-not $charters -or $charters.Count -eq 0) {
        [Console]::Error.WriteLine("no charter found for role: $Role")
        exit 1
    }
}

if ($charters.Count -eq 0) {
    Write-Info "No charters found under $charterRoot" 'Yellow'
    exit 0
}

# ------------------------------------------------------------------
# Sync each charter → role file
# ------------------------------------------------------------------
$synced = 0
$skipped = 0
$errors = 0

Write-Info "[sync-roles] charters: $($charters.Count) | dry-run=$DryRun | force=$Force"

foreach ($c in $charters) {
    $roleFile = Join-Path $rolesRoot "$($c.Role).md"
    $body = Get-Content $c.Charter -Raw -Encoding UTF8
    $banner = Get-Banner -RoleName $c.Role
    $combined = $banner + $body

    # Unchanged? Skip unless -Force.
    if ((-not $Force) -and (Test-BodyEquivalent -RolePath $roleFile -NewBody $body)) {
        Write-Info "  [skip] $($c.Role): unchanged" 'DarkGray'
        $skipped++
        continue
    }

    if ($DryRun) {
        $exists = Test-Path $roleFile
        $verb = if ($exists) { 'would-update' } else { 'would-create' }
        Write-Info "  [$verb] $roleFile" 'Yellow'
        continue
    }

    # If the target is currently a hardlink (nlink>1), detect + unlink first so we
    # don't write through it back into the charter. We test by writing to a tmp
    # first, then atomic-replace.
    $tmp = "$roleFile.tmp"
    try {
        # Overwrite any existing hardlink: the safest is to delete target, then write.
        # This IS the "break the hardlink" step, which is the whole point of this script.
        if (Test-Path $roleFile) {
            Remove-Item $roleFile -Force
        }
        # Use .NET to write UTF-8 without BOM (BOM confuses some tooling on Windows).
        [System.IO.File]::WriteAllText($roleFile, $combined, (New-Object System.Text.UTF8Encoding $false))
        Write-Info "  [sync] $($c.Role) -> $roleFile ($($body.Length) chars)" 'Green'
        $synced++
    } catch {
        [Console]::Error.WriteLine("  [FAIL] $($c.Role): $_")
        $errors++
    } finally {
        if (Test-Path $tmp) { Remove-Item $tmp -Force -ErrorAction SilentlyContinue }
    }
}

# ------------------------------------------------------------------
# Orphan report (role files without a charter — e.g. official defaults)
# ------------------------------------------------------------------
$charterNames = $charters | ForEach-Object { $_.Role }
$roleFiles = Get-ChildItem $rolesRoot -Filter '*.md' -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -notlike '*.bak' -and $_.Name -notlike '*.orphan-*' }
$orphans = @()
foreach ($rf in $roleFiles) {
    $name = [IO.Path]::GetFileNameWithoutExtension($rf.Name)
    if ($charterNames -notcontains $name) { $orphans += $name }
}

if ($orphans.Count -gt 0 -and -not $Quiet) {
    Write-Info ""
    Write-Info "[sync-roles] orphan role files (no matching charter, left untouched):" 'DarkYellow'
    foreach ($o in $orphans) { Write-Info "    $o" 'DarkYellow' }
}

Write-Info ""
Write-Info "[sync-roles] synced=$synced skipped=$skipped errors=$errors orphans=$($orphans.Count)" 'Cyan'

if ($errors -gt 0) { exit 2 }
exit 0
