"""Runtime credential store.

JSON-on-disk metadata lives under runtime_state_path("credentials",
"runtime_credentials.json"). Secret material is stored behind a secret backend
and is rehydrated only for internal dispatch callers.

Thread-safe: all read/write operations acquire a store-level lock.
"""

from __future__ import annotations

import json
import logging
import os
import sys
import threading
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Protocol

from _atomic_io import CrossProcessFileLock, atomic_write_json
from project_paths import runtime_state_path

from models.credentials import (
    RuntimeCredential,
    RuntimeCredentialCreate,
    RuntimeCredentialPublic,
    RuntimeCredentialUpdate,
)


SCHEMA_VERSION = 2
DEFAULT_FILENAME = "runtime_credentials.json"
SECRET_REF_FIELD = "api_key_secret_ref"
SECRET_FILE_SCHEMA_VERSION = 1
SECRET_BACKEND_ENV = "LITASSIST_CREDENTIAL_SECRET_BACKEND"
KEYRING_SERVICE_NAME = "literature-assistant.runtime-credentials"

logger = logging.getLogger("CredentialStore")


def default_credentials_path() -> Path:
    return runtime_state_path("credentials", DEFAULT_FILENAME)


class CredentialNotFoundError(LookupError):
    pass


class CredentialSchemaError(ValueError):
    pass


class CredentialSecretStorageError(RuntimeError):
    """Raised when the selected secret backend cannot store or return secrets."""


class CredentialSecretMissingError(CredentialSecretStorageError):
    """Raised when metadata references a secret that no longer exists."""


class CredentialSecretBackend(Protocol):
    """Backend contract for runtime credential material.

    Implementations receive opaque secret refs generated by the store and must
    never include the secret value in exceptions or logs.
    """

    backend_name: str

    def create_secret_ref(self, credential_id: str) -> str:
        """Return a new opaque ref for one credential's API key."""
        ...

    def store_secret(self, secret_ref: str, secret: str) -> None:
        """Persist secret material for the given ref."""
        ...

    def get_secret(self, secret_ref: str) -> str:
        """Return secret material for the given ref."""
        ...

    def delete_secret(self, secret_ref: str) -> None:
        """Delete secret material for the given ref."""
        ...


@dataclass(frozen=True)
class _LoadedCredential:
    credential: RuntimeCredential
    secret_ref: str


def _atomic_write_json(path: Path, payload: dict) -> None:
    """Backwards-compat wrapper preserved for any external import
    public surface). New code should call ``_atomic_io.atomic_write_json``
    directly. This delegates to the shared implementation.
    """
    atomic_write_json(path, payload)


def _secret_file_path_for_credentials_path(path: Path) -> Path:
    """Return the plaintext fallback secret file path for an isolated store."""

    return path.with_name(f"{path.stem}.secrets.json")


def _path_equals(left: Path, right: Path) -> bool:
    """Return true when two paths resolve to the same filesystem target."""

    try:
        return left.resolve() == right.resolve()
    except OSError:
        return left.absolute() == right.absolute()


def _is_default_credentials_path(path: Path) -> bool:
    """Return whether a store path is the production runtime metadata path."""

    return _path_equals(path, default_credentials_path())


def _is_frozen() -> bool:
    """Return True when running as a frozen PyInstaller bundle."""
    return getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS")


class PlaintextFileCredentialSecretBackend:
    """Last-resort local secret backend for tests and explicit fallback.

    Why:
        Unit tests and isolated temporary stores need deterministic local
        cleanup without touching a user's OS keyring. Production default stores
        use the keyring backend unless this fallback is explicitly selected.
    """

    backend_name = "plaintext_file"

    def __init__(self, path: Path) -> None:
        self._path = Path(path)
        self._lock = threading.RLock()
        self._file_lock_path = self._path.with_suffix(f"{self._path.suffix}.lock")

    @property
    def path(self) -> Path:
        return self._path

    def create_secret_ref(self, credential_id: str) -> str:
        cleaned = str(credential_id or "").strip()
        if not cleaned:
            raise CredentialSecretStorageError("credential id is required for secret ref")
        return f"file:{cleaned}:{uuid.uuid4().hex}:api_key"

    def store_secret(self, secret_ref: str, secret: str) -> None:
        ref = self._validate_ref(secret_ref)
        value = str(secret or "")
        if not value:
            raise CredentialSecretStorageError("refusing to store empty credential secret")
        with self._lock, CrossProcessFileLock(self._file_lock_path):
            payload = self._load_payload()
            payload["secrets"][ref] = value
            self._write_payload(payload)

    def get_secret(self, secret_ref: str) -> str:
        ref = self._validate_ref(secret_ref)
        with self._lock, CrossProcessFileLock(self._file_lock_path):
            payload = self._load_payload()
            value = payload["secrets"].get(ref)
        if not isinstance(value, str) or not value:
            raise CredentialSecretMissingError("credential secret is missing from file backend")
        return value

    def delete_secret(self, secret_ref: str) -> None:
        ref = self._validate_ref(secret_ref)
        with self._lock, CrossProcessFileLock(self._file_lock_path):
            payload = self._load_payload()
            if ref in payload["secrets"]:
                del payload["secrets"][ref]
                self._write_payload(payload)

    def _validate_ref(self, secret_ref: str) -> str:
        ref = str(secret_ref or "").strip()
        if not ref.startswith("file:") or ":api_key" not in ref:
            raise CredentialSecretStorageError("credential secret ref does not belong to file backend")
        return ref

    def _empty_payload(self) -> dict[str, Any]:
        return {
            "schema_version": SECRET_FILE_SCHEMA_VERSION,
            "updated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "secrets": {},
        }

    def _load_payload(self) -> dict[str, Any]:
        if not self._path.exists():
            return self._empty_payload()
        try:
            payload = json.loads(self._path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise CredentialSecretStorageError(
                "credential secret fallback file is not valid JSON"
            ) from exc
        if not isinstance(payload, dict):
            raise CredentialSecretStorageError("credential secret fallback root must be an object")
        if payload.get("schema_version") != SECRET_FILE_SCHEMA_VERSION:
            raise CredentialSecretStorageError("unsupported credential secret fallback schema")
        secrets = payload.get("secrets")
        if not isinstance(secrets, dict):
            raise CredentialSecretStorageError("credential secret fallback secrets must be an object")
        return payload

    def _write_payload(self, payload: dict[str, Any]) -> None:
        payload["updated_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        _atomic_write_json(self._path, payload)


class KeyringCredentialSecretBackend:
    """OS keyring backend for runtime credential material."""

    backend_name = "keyring"

    def __init__(self, service_name: str = KEYRING_SERVICE_NAME) -> None:
        cleaned = str(service_name or "").strip()
        if not cleaned:
            raise CredentialSecretStorageError("keyring service name is required")
        self._service_name = cleaned

    def create_secret_ref(self, credential_id: str) -> str:
        cleaned = str(credential_id or "").strip()
        if not cleaned:
            raise CredentialSecretStorageError("credential id is required for secret ref")
        return f"keyring:{cleaned}:{uuid.uuid4().hex}:api_key"

    def store_secret(self, secret_ref: str, secret: str) -> None:
        ref = self._validate_ref(secret_ref)
        value = str(secret or "")
        if not value:
            raise CredentialSecretStorageError("refusing to store empty credential secret")
        keyring = self._keyring_module()
        try:
            keyring.set_password(self._service_name, ref, value)
        except Exception as exc:  # noqa: BLE001 - backend availability varies by OS.
            raise CredentialSecretStorageError(
                f"keyring secret store failed: {type(exc).__name__}"
            ) from exc

    def get_secret(self, secret_ref: str) -> str:
        ref = self._validate_ref(secret_ref)
        keyring = self._keyring_module()
        try:
            value = keyring.get_password(self._service_name, ref)
        except Exception as exc:  # noqa: BLE001 - backend availability varies by OS.
            raise CredentialSecretStorageError(
                f"keyring secret read failed: {type(exc).__name__}"
            ) from exc
        if not isinstance(value, str) or not value:
            raise CredentialSecretMissingError("credential secret is missing from keyring")
        return value

    def delete_secret(self, secret_ref: str) -> None:
        ref = self._validate_ref(secret_ref)
        keyring = self._keyring_module()
        try:
            keyring.delete_password(self._service_name, ref)
        except Exception as exc:  # noqa: BLE001 - PasswordDeleteError means already gone.
            if type(exc).__name__ == "PasswordDeleteError":
                return
            raise CredentialSecretStorageError(
                f"keyring secret delete failed: {type(exc).__name__}"
            ) from exc

    def _validate_ref(self, secret_ref: str) -> str:
        ref = str(secret_ref or "").strip()
        if not ref.startswith("keyring:") or ":api_key" not in ref:
            raise CredentialSecretStorageError("credential secret ref does not belong to keyring")
        return ref

    def _keyring_module(self) -> Any:
        try:
            import keyring
        except Exception as exc:  # noqa: BLE001 - optional dependency may be absent.
            raise CredentialSecretStorageError(
                "keyring package is unavailable; set "
                f"{SECRET_BACKEND_ENV}=plaintext_file for an explicit local fallback"
            ) from exc

        try:
            backend = keyring.get_keyring()
        except Exception as exc:  # noqa: BLE001 - backend probing is platform specific.
            raise CredentialSecretStorageError(
                f"keyring backend probe failed: {type(exc).__name__}"
            ) from exc
        backend_name = f"{type(backend).__module__}.{type(backend).__name__}".lower()
        priority = getattr(backend, "priority", 0)
        if "fail" in backend_name or "null" in backend_name or float(priority or 0) <= 0:
            raise CredentialSecretStorageError(
                "no usable OS keyring backend is available; set "
                f"{SECRET_BACKEND_ENV}=plaintext_file for an explicit local fallback"
            )
        return keyring


def _select_secret_backend(path: Path) -> CredentialSecretBackend:
    """Choose a secret backend for a credential metadata path.

    Why:
        A custom metadata path is not proof that plaintext secret storage is
        acceptable. Plaintext files remain available only through explicit
        local opt-in for tests and emergency recovery.

    Security:
        Frozen applications (PyInstaller bundles) must never use plaintext_file
        backend to prevent API key leakage in %APPDATA%.
    """

    raw = os.environ.get(SECRET_BACKEND_ENV, "").strip().lower()

    # Frozen application security gate: refuse plaintext backend
    if _is_frozen() and raw in {"plaintext_file", "file", "local_file"}:
        raise CredentialSecretStorageError(
            f"Plaintext credential storage is disabled in packaged applications. "
            f"Remove {SECRET_BACKEND_ENV}={raw} or set it to 'keyring'."
        )

    if raw in {"plaintext_file", "file", "local_file"}:
        return PlaintextFileCredentialSecretBackend(_secret_file_path_for_credentials_path(path))
    if raw in {"keyring", "os_keyring"}:
        return KeyringCredentialSecretBackend()
    if raw not in {"", "auto"}:
        raise CredentialSecretStorageError(
            f"unsupported {SECRET_BACKEND_ENV} value: {raw!r}"
        )
    return KeyringCredentialSecretBackend()


class RuntimeCredentialStore:
    """Persistent runtime credential registry.

    File layout:
        {
            "schema_version": 2,
            "updated_at": "2026-05-08T...",
            "credentials": [
                {
                    ...RuntimeCredential metadata excluding api_key,
                    "api_key_secret_ref": "keyring:cred_...:...:api_key"
                }
            ]
        }

    Public API never returns api_key; callers receive RuntimeCredentialPublic.
    Internal API returns RuntimeCredential (for dispatcher use only).
    """

    def __init__(
        self,
        path: Path | None = None,
        *,
        secret_backend: CredentialSecretBackend | None = None,
    ) -> None:
        self._path = Path(path) if path else default_credentials_path()
        self._secret_backend = secret_backend or _select_secret_backend(self._path)
        self._lock = threading.Lock()
        self._file_lock_path = self._path.with_suffix(f"{self._path.suffix}.lock")

    @property
    def path(self) -> Path:
        return self._path

    @property
    def secret_backend_name(self) -> str:
        return self._secret_backend.backend_name

    # ------------------------------------------------------------------ load

    def _load_raw(self) -> dict[str, Any]:
        if not self._path.exists():
            return {
                "schema_version": SCHEMA_VERSION,
                "updated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                "credentials": [],
            }
        try:
            data = json.loads(self._path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise CredentialSchemaError(
                f"runtime credentials file is not valid JSON: {self._path}"
            ) from exc
        if not isinstance(data, dict):
            raise CredentialSchemaError("runtime credentials root must be an object")
        version = data.get("schema_version")
        if not isinstance(version, int):
            raise CredentialSchemaError("missing or non-int schema_version")
        if version > SCHEMA_VERSION:
            raise CredentialSchemaError(
                f"runtime credentials schema_version={version} > supported "
                f"{SCHEMA_VERSION}; refusing to read"
            )
        creds = data.get("credentials")
        if not isinstance(creds, list):
            raise CredentialSchemaError("credentials must be a list")
        return data

    def _load_credentials(self) -> list[RuntimeCredential]:
        return [record.credential for record in self._load_records()]

    def _load_records(self, *, migrate_plaintext: bool = True) -> list[_LoadedCredential]:
        data = self._load_raw()
        out: list[_LoadedCredential] = []
        needs_migration = False
        for raw in data["credentials"]:
            if not isinstance(raw, dict):
                raise CredentialSchemaError("each credential must be an object")
            out.append(self._deserialize_record(raw))
            if "api_key" in raw:
                needs_migration = True
        if needs_migration and migrate_plaintext:
            self._persist_records(out)
        return out

    def _deserialize_record(self, raw: dict[str, Any]) -> _LoadedCredential:
        working = dict(raw)
        legacy_secret = working.pop("api_key", None)
        secret_ref_value = working.pop(SECRET_REF_FIELD, None)
        if legacy_secret is not None:
            if not isinstance(legacy_secret, str) or not legacy_secret.strip():
                raise CredentialSchemaError("credential api_key must be a non-empty string")
            working["api_key"] = legacy_secret
            try:
                credential = RuntimeCredential.model_validate(working)
            except Exception as exc:
                raise CredentialSchemaError(
                    f"credential entry rejected by validator: {exc}"
                ) from exc
            return _LoadedCredential(
                credential=credential,
                secret_ref=self._secret_backend.create_secret_ref(credential.credential_id),
            )

        if not isinstance(secret_ref_value, str) or not secret_ref_value.strip():
            raise CredentialSchemaError(f"credential is missing {SECRET_REF_FIELD}")
        working["api_key"] = self._secret_backend.get_secret(secret_ref_value)
        try:
            credential = RuntimeCredential.model_validate(working)
        except Exception as exc:
            raise CredentialSchemaError(
                f"credential entry rejected by validator: {exc}"
            ) from exc
        return _LoadedCredential(credential=credential, secret_ref=secret_ref_value)

    # ----------------------------------------------------------------- write

    def _persist(self, credentials: Iterable[RuntimeCredential]) -> None:
        records = [
            _LoadedCredential(
                credential=credential,
                secret_ref=self._secret_backend.create_secret_ref(credential.credential_id),
            )
            for credential in credentials
        ]
        self._persist_records(records)

    def _persist_records(self, records: Iterable[_LoadedCredential]) -> None:
        materialized = list(records)
        for record in materialized:
            self._secret_backend.store_secret(record.secret_ref, record.credential.api_key)
        payload = {
            "schema_version": SCHEMA_VERSION,
            "updated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "credentials": [self._serialize_record(record) for record in materialized],
        }
        _atomic_write_json(self._path, payload)

    def _serialize_record(self, record: _LoadedCredential) -> dict[str, Any]:
        payload = record.credential.model_dump(mode="json", exclude={"api_key"})
        payload[SECRET_REF_FIELD] = record.secret_ref
        return payload

    def _delete_secret_quietly(self, secret_ref: str) -> None:
        try:
            self._secret_backend.delete_secret(secret_ref)
        except CredentialSecretStorageError as exc:
            logger.warning("credential secret delete skipped: %s", type(exc).__name__)

    # ---------------------------------------------------------- public read

    def list_public(
        self,
        *,
        category: str | None = None,
        enabled_only: bool = False,
    ) -> list[RuntimeCredentialPublic]:
        with self._lock, CrossProcessFileLock(self._file_lock_path):
            records = self._load_records()
        out: list[RuntimeCredentialPublic] = []
        for record in records:
            c = record.credential
            if category and c.category.value != category:
                continue
            if enabled_only and not c.enabled:
                continue
            out.append(c.to_public())
        return out

    def get_public(self, credential_id: str) -> RuntimeCredentialPublic:
        with self._lock, CrossProcessFileLock(self._file_lock_path):
            records = self._load_records()
        for record in records:
            c = record.credential
            if c.credential_id == credential_id:
                return c.to_public()
        raise CredentialNotFoundError(credential_id)

    # -------------------------------------------------------- internal read

    def list_internal(
        self,
        *,
        category: str | None = None,
        enabled_only: bool = True,
    ) -> list[RuntimeCredential]:
        """Internal API for dispatcher / pool merge. Includes api_key.

        Caller responsibility: never pass results into log / API response.
        """
        with self._lock, CrossProcessFileLock(self._file_lock_path):
            records = self._load_records()
        out: list[RuntimeCredential] = []
        for record in records:
            c = record.credential
            if category and c.category.value != category:
                continue
            if enabled_only and not c.enabled:
                continue
            out.append(c)
        return out

    def get_internal(self, credential_id: str) -> RuntimeCredential:
        with self._lock, CrossProcessFileLock(self._file_lock_path):
            records = self._load_records()
        for record in records:
            c = record.credential
            if c.credential_id == credential_id:
                return c
        raise CredentialNotFoundError(credential_id)

    # ---------------------------------------------------------------- write

    def create(self, body: RuntimeCredentialCreate) -> RuntimeCredentialPublic:
        cred = RuntimeCredential.from_create(body)
        record = _LoadedCredential(
            credential=cred,
            secret_ref=self._secret_backend.create_secret_ref(cred.credential_id),
        )
        with self._lock, CrossProcessFileLock(self._file_lock_path):
            existing = self._load_records()
            updated_records = [*existing, record]
            try:
                self._persist_records(updated_records)
            except Exception:
                self._delete_secret_quietly(record.secret_ref)
                raise
        return cred.to_public()

    def update(
        self, credential_id: str, body: RuntimeCredentialUpdate
    ) -> RuntimeCredentialPublic:
        with self._lock, CrossProcessFileLock(self._file_lock_path):
            existing = self._load_records()
            update_payload = body.model_dump(exclude_unset=True)
            rotates_secret = update_payload.get("api_key") is not None
            for i, record in enumerate(existing):
                c = record.credential
                if c.credential_id == credential_id:
                    updated = c.with_update(body)
                    new_secret_ref = (
                        self._secret_backend.create_secret_ref(credential_id)
                        if rotates_secret
                        else record.secret_ref
                    )
                    updated_record = _LoadedCredential(
                        credential=updated,
                        secret_ref=new_secret_ref,
                    )
                    existing[i] = updated_record
                    try:
                        self._persist_records(existing)
                    except Exception:
                        if rotates_secret:
                            self._delete_secret_quietly(new_secret_ref)
                        raise
                    if rotates_secret and new_secret_ref != record.secret_ref:
                        self._delete_secret_quietly(record.secret_ref)
                    return updated.to_public()
        raise CredentialNotFoundError(credential_id)

    def delete(self, credential_id: str) -> bool:
        with self._lock, CrossProcessFileLock(self._file_lock_path):
            existing = self._load_records()
            for i, record in enumerate(existing):
                c = record.credential
                if c.credential_id == credential_id:
                    del existing[i]
                    self._persist_records(existing)
                    self._delete_secret_quietly(record.secret_ref)
                    return True
        return False


__all__ = [
    "CredentialNotFoundError",
    "CredentialSchemaError",
    "CredentialSecretBackend",
    "CredentialSecretMissingError",
    "CredentialSecretStorageError",
    "DEFAULT_FILENAME",
    "KEYRING_SERVICE_NAME",
    "PlaintextFileCredentialSecretBackend",
    "KeyringCredentialSecretBackend",
    "RuntimeCredentialStore",
    "SCHEMA_VERSION",
    "SECRET_BACKEND_ENV",
    "SECRET_REF_FIELD",
    "default_credentials_path",
]
