"""SQLite persistence for saved Inspiration sparks."""

from __future__ import annotations

import json
import sqlite3
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from project_paths import runtime_state_path


DEFAULT_DB_FILENAME = "inspiration_store.sqlite3"
MAX_QUERY_CHARS = 500
MAX_NOTES_CHARS = 2000
MAX_TAGS = 20
MAX_TAG_CHARS = 80


class InspirationStoreError(RuntimeError):
    """Raised when the local Inspiration store cannot satisfy a request."""


@dataclass(frozen=True)
class SavedInspirationRecord:
    """Stored Inspiration spark payload.

    Args:
        saved_id: Stable local id generated by the store.
        project_id: Optional project scope for filtering saved sparks.
        query: User query that produced or contextualized the spark.
        spark: Public SparkResponse-shaped JSON object.
        notes: User or workflow notes attached to the saved spark.
        source: Local provenance label such as ``generated`` or ``manual``.
        tags: Normalized user/workflow tags for local filtering.
        metadata: JSON-safe auxiliary fields; never stores credentials.
        created_at: UTC ISO-8601 timestamp.
        updated_at: UTC ISO-8601 timestamp.
        version: Monotonic row version incremented on update.
    """

    saved_id: str
    project_id: str | None
    query: str
    spark: dict[str, Any]
    notes: str
    source: str
    tags: tuple[str, ...]
    metadata: dict[str, Any]
    created_at: str
    updated_at: str
    version: int

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-safe representation for API boundary models."""

        return {
            "saved_id": self.saved_id,
            "project_id": self.project_id,
            "query": self.query,
            "spark": dict(self.spark),
            "notes": self.notes,
            "source": self.source,
            "tags": list(self.tags),
            "metadata": dict(self.metadata),
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "version": self.version,
        }


@dataclass(frozen=True)
class SavedInspirationList:
    """Paginated result for saved Inspiration sparks."""

    items: tuple[SavedInspirationRecord, ...]
    total: int
    page: int
    page_size: int


def default_db_path() -> Path:
    """Return the local runtime-state SQLite path for saved inspirations."""

    path = runtime_state_path(DEFAULT_DB_FILENAME)
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


class InspirationStore:
    """SQLite-backed CRUD store for saved Inspiration sparks."""

    def __init__(self, db_path: str | Path | None = None) -> None:
        resolved = Path(db_path).expanduser().resolve() if db_path is not None else default_db_path()
        resolved.parent.mkdir(parents=True, exist_ok=True)
        self.db_path = str(resolved)
        self._init_schema()

    def create(
        self,
        *,
        spark: dict[str, Any],
        project_id: str | None = None,
        query: str = "",
        notes: str = "",
        source: str = "generated",
        tags: list[str] | tuple[str, ...] | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> SavedInspirationRecord:
        """Persist one spark and return the stored record.

        Raises:
            ValueError: If required fields are malformed or exceed local bounds.
            InspirationStoreError: If SQLite rejects the write.
        """

        normalized_spark = _normalize_spark(spark)
        now = _utc_now()
        record = SavedInspirationRecord(
            saved_id=f"ins_{uuid.uuid4().hex}",
            project_id=_normalize_optional_text(project_id, "project_id", max_chars=160),
            query=_normalize_text(query, "query", max_chars=MAX_QUERY_CHARS),
            spark=normalized_spark,
            notes=_normalize_text(notes, "notes", max_chars=MAX_NOTES_CHARS),
            source=_normalize_source(source),
            tags=tuple(_normalize_tags(tags or [])),
            metadata=_normalize_metadata(metadata or {}),
            created_at=now,
            updated_at=now,
            version=1,
        )
        with self._open() as conn:
            try:
                conn.execute(
                    """
                    INSERT INTO inspiration_store (
                        saved_id, project_id, query, spark_json, notes, source,
                        tags_json, metadata_json, created_at, updated_at, version
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    _record_to_row(record),
                )
            except sqlite3.Error as exc:
                raise InspirationStoreError(f"failed to create inspiration record: {exc}") from exc
        return record

    def get(self, saved_id: str) -> SavedInspirationRecord | None:
        """Load a single record by local saved id."""

        normalized_id = _normalize_saved_id(saved_id)
        with self._open() as conn:
            row = conn.execute(
                "SELECT * FROM inspiration_store WHERE saved_id = ?",
                (normalized_id,),
            ).fetchone()
        return _row_to_record(row) if row is not None else None

    def list(
        self,
        *,
        project_id: str | None = None,
        source: str | None = None,
        tag: str | None = None,
        page: int = 1,
        page_size: int = 50,
    ) -> SavedInspirationList:
        """Return saved inspirations ordered by newest update first."""

        normalized_page = _normalize_int(page, "page", minimum=1, maximum=1_000_000)
        normalized_page_size = _normalize_int(page_size, "page_size", minimum=1, maximum=100)
        where_parts: list[str] = []
        params: list[Any] = []

        normalized_project_id = _normalize_optional_text(project_id, "project_id", max_chars=160)
        if normalized_project_id:
            where_parts.append("project_id = ?")
            params.append(normalized_project_id)

        normalized_source = _normalize_optional_source(source)
        if normalized_source:
            where_parts.append("source = ?")
            params.append(normalized_source)

        normalized_tag = _normalize_optional_text(tag, "tag", max_chars=MAX_TAG_CHARS)
        if normalized_tag:
            where_parts.append("tags_json LIKE ?")
            params.append(f'%"{_escape_like(normalized_tag)}"%')

        where = f" WHERE {' AND '.join(where_parts)}" if where_parts else ""
        offset = (normalized_page - 1) * normalized_page_size

        with self._open() as conn:
            total_row = conn.execute(
                f"SELECT COUNT(*) AS count FROM inspiration_store{where}",
                tuple(params),
            ).fetchone()
            rows = conn.execute(
                f"""
                SELECT * FROM inspiration_store{where}
                ORDER BY updated_at DESC, saved_id ASC
                LIMIT ? OFFSET ?
                """,
                tuple(params + [normalized_page_size, offset]),
            ).fetchall()

        total = int(total_row["count"]) if total_row is not None else 0
        return SavedInspirationList(
            items=tuple(_row_to_record(row) for row in rows),
            total=total,
            page=normalized_page,
            page_size=normalized_page_size,
        )

    def update(
        self,
        saved_id: str,
        *,
        spark: dict[str, Any] | None = None,
        project_id: str | None = None,
        clear_project_id: bool = False,
        query: str | None = None,
        notes: str | None = None,
        source: str | None = None,
        tags: list[str] | tuple[str, ...] | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> SavedInspirationRecord | None:
        """Update an existing saved spark and return the fresh record."""

        current = self.get(saved_id)
        if current is None:
            return None

        updated_project_id = current.project_id
        if clear_project_id:
            updated_project_id = None
        elif project_id is not None:
            updated_project_id = _normalize_optional_text(project_id, "project_id", max_chars=160)

        updated = SavedInspirationRecord(
            saved_id=current.saved_id,
            project_id=updated_project_id,
            query=current.query if query is None else _normalize_text(query, "query", max_chars=MAX_QUERY_CHARS),
            spark=current.spark if spark is None else _normalize_spark(spark),
            notes=current.notes if notes is None else _normalize_text(notes, "notes", max_chars=MAX_NOTES_CHARS),
            source=current.source if source is None else _normalize_source(source),
            tags=current.tags if tags is None else tuple(_normalize_tags(tags)),
            metadata=current.metadata if metadata is None else _normalize_metadata(metadata),
            created_at=current.created_at,
            updated_at=_utc_now(),
            version=current.version + 1,
        )

        with self._open() as conn:
            try:
                conn.execute(
                    """
                    UPDATE inspiration_store
                    SET project_id = ?, query = ?, spark_json = ?, notes = ?,
                        source = ?, tags_json = ?, metadata_json = ?,
                        updated_at = ?, version = ?
                    WHERE saved_id = ?
                    """,
                    (
                        updated.project_id,
                        updated.query,
                        _json_dumps(updated.spark),
                        updated.notes,
                        updated.source,
                        _json_dumps(list(updated.tags)),
                        _json_dumps(updated.metadata),
                        updated.updated_at,
                        updated.version,
                        updated.saved_id,
                    ),
                )
            except sqlite3.Error as exc:
                raise InspirationStoreError(f"failed to update inspiration record: {exc}") from exc
        return updated

    def delete(self, saved_id: str) -> bool:
        """Delete one saved spark by id."""

        normalized_id = _normalize_saved_id(saved_id)
        with self._open() as conn:
            try:
                cursor = conn.execute(
                    "DELETE FROM inspiration_store WHERE saved_id = ?",
                    (normalized_id,),
                )
            except sqlite3.Error as exc:
                raise InspirationStoreError(f"failed to delete inspiration record: {exc}") from exc
        return cursor.rowcount > 0

    def _open(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path, timeout=10.0)
        conn.row_factory = sqlite3.Row
        try:
            conn.execute("PRAGMA journal_mode = WAL")
            conn.execute("PRAGMA busy_timeout = 10000")
            conn.execute("PRAGMA synchronous = NORMAL")
        except sqlite3.DatabaseError:
            pass
        return conn

    def _init_schema(self) -> None:
        with self._open() as conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS inspiration_store (
                    saved_id TEXT PRIMARY KEY,
                    project_id TEXT,
                    query TEXT NOT NULL,
                    spark_json TEXT NOT NULL,
                    notes TEXT NOT NULL,
                    source TEXT NOT NULL,
                    tags_json TEXT NOT NULL,
                    metadata_json TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    version INTEGER NOT NULL
                )
                """
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_inspiration_store_project ON inspiration_store(project_id)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_inspiration_store_updated ON inspiration_store(updated_at)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_inspiration_store_source ON inspiration_store(source)"
            )


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _json_dumps(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _json_loads(value: Any, fallback: Any) -> Any:
    if not isinstance(value, str) or not value.strip():
        return fallback
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        return fallback


def _normalize_text(value: str | None, field_name: str, *, max_chars: int) -> str:
    if value is None:
        return ""
    if not isinstance(value, str):
        raise ValueError(f"{field_name} must be a string")
    normalized = value.strip()
    if len(normalized) > max_chars:
        raise ValueError(f"{field_name} must be at most {max_chars} characters")
    return normalized


def _normalize_optional_text(value: object, field_name: str, *, max_chars: int) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str):
        raise ValueError(f"{field_name} must be a string or null")
    normalized = value.strip()
    if not normalized:
        return None
    if len(normalized) > max_chars:
        raise ValueError(f"{field_name} must be at most {max_chars} characters")
    return normalized


def _normalize_saved_id(value: str) -> str:
    normalized = _normalize_text(value, "saved_id", max_chars=120)
    if not normalized:
        raise ValueError("saved_id is required")
    return normalized


def _normalize_int(value: int, field_name: str, *, minimum: int, maximum: int) -> int:
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError(f"{field_name} must be an integer")
    if value < minimum or value > maximum:
        raise ValueError(f"{field_name} must be between {minimum} and {maximum}")
    return value


def _normalize_source(value: str) -> str:
    normalized = _normalize_text(value, "source", max_chars=40)
    if normalized not in {"generated", "manual", "imported"}:
        raise ValueError("source must be generated, manual, or imported")
    return normalized


def _normalize_optional_source(value: str | None) -> str | None:
    if value is None:
        return None
    return _normalize_source(value)


def _normalize_tags(tags: list[str] | tuple[str, ...]) -> list[str]:
    if not isinstance(tags, (list, tuple)):
        raise ValueError("tags must be a list of strings")
    normalized: list[str] = []
    seen: set[str] = set()
    for raw_tag in tags:
        if not isinstance(raw_tag, str):
            raise ValueError("tags must contain only strings")
        tag = raw_tag.strip()
        if not tag:
            continue
        if len(tag) > MAX_TAG_CHARS:
            raise ValueError(f"tags must be at most {MAX_TAG_CHARS} characters each")
        if tag in seen:
            continue
        normalized.append(tag)
        seen.add(tag)
        if len(normalized) > MAX_TAGS:
            raise ValueError(f"tags must contain at most {MAX_TAGS} items")
    return normalized


def _normalize_spark(value: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError("spark must be a JSON object")
    spark_id = value.get("id")
    content = value.get("content")
    spark_type = value.get("spark_type")
    if not isinstance(spark_id, str) or not spark_id.strip():
        raise ValueError("spark.id is required")
    if not isinstance(content, str) or not content.strip():
        raise ValueError("spark.content is required")
    if not isinstance(spark_type, str) or not spark_type.strip():
        raise ValueError("spark.spark_type is required")
    _json_dumps(value)
    return dict(value)


def _normalize_metadata(value: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError("metadata must be a JSON object")
    _json_dumps(value)
    return dict(value)


def _escape_like(value: str) -> str:
    return value.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")


def _record_to_row(record: SavedInspirationRecord) -> tuple[Any, ...]:
    return (
        record.saved_id,
        record.project_id,
        record.query,
        _json_dumps(record.spark),
        record.notes,
        record.source,
        _json_dumps(list(record.tags)),
        _json_dumps(record.metadata),
        record.created_at,
        record.updated_at,
        record.version,
    )


def _row_to_record(row: sqlite3.Row) -> SavedInspirationRecord:
    spark = _json_loads(row["spark_json"], {})
    tags = _json_loads(row["tags_json"], [])
    metadata = _json_loads(row["metadata_json"], {})
    return SavedInspirationRecord(
        saved_id=str(row["saved_id"]),
        project_id=str(row["project_id"]) if row["project_id"] is not None else None,
        query=str(row["query"]),
        spark=spark if isinstance(spark, dict) else {},
        notes=str(row["notes"]),
        source=str(row["source"]),
        tags=tuple(item for item in tags if isinstance(item, str)) if isinstance(tags, list) else (),
        metadata=metadata if isinstance(metadata, dict) else {},
        created_at=str(row["created_at"]),
        updated_at=str(row["updated_at"]),
        version=int(row["version"]),
    )


__all__ = [
    "InspirationStore",
    "InspirationStoreError",
    "SavedInspirationList",
    "SavedInspirationRecord",
    "default_db_path",
]
